package com.liugx.testsystem.mapper;

import com.liugx.testsystem.model.PaperAndQuestion;
import com.liugx.testsystem.model.PaperAndQuestionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PaperAndQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paperandques
     *
     * @mbg.generated Mon Nov 09 10:13:38 CST 2020
     */
    long countByExample(PaperAndQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paperandques
     *
     * @mbg.generated Mon Nov 09 10:13:38 CST 2020
     */
    int deleteByExample(PaperAndQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paperandques
     *
     * @mbg.generated Mon Nov 09 10:13:38 CST 2020
     */
    int insert(PaperAndQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paperandques
     *
     * @mbg.generated Mon Nov 09 10:13:38 CST 2020
     */
    int insertSelective(PaperAndQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paperandques
     *
     * @mbg.generated Mon Nov 09 10:13:38 CST 2020
     */
    List<PaperAndQuestion> selectByExampleWithRowbounds(PaperAndQuestionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paperandques
     *
     * @mbg.generated Mon Nov 09 10:13:38 CST 2020
     */
    List<PaperAndQuestion> selectByExample(PaperAndQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paperandques
     *
     * @mbg.generated Mon Nov 09 10:13:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") PaperAndQuestion record, @Param("example") PaperAndQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paperandques
     *
     * @mbg.generated Mon Nov 09 10:13:38 CST 2020
     */
    int updateByExample(@Param("record") PaperAndQuestion record, @Param("example") PaperAndQuestionExample example);
}