package com.liugx.testsystem.mapper;

import com.liugx.testsystem.model.UserTopic;
import com.liugx.testsystem.model.UserTopicExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UserTopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    long countByExample(UserTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    int deleteByExample(UserTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    int insert(UserTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    int insertSelective(UserTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    List<UserTopic> selectByExampleWithRowbounds(UserTopicExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    List<UserTopic> selectByExample(UserTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    UserTopic selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserTopic record, @Param("example") UserTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    int updateByExample(@Param("record") UserTopic record, @Param("example") UserTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    int updateByPrimaryKeySelective(UserTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    int updateByPrimaryKey(UserTopic record);
}