package com.liugx.testsystem.model;

public class PaperAndQuestion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paperandques.paperid
     *
     * @mbg.generated Mon Nov 09 10:13:38 CST 2020
     */
    private Long paperid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paperandques.questionid
     *
     * @mbg.generated Mon Nov 09 10:13:38 CST 2020
     */
    private Long questionid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paperandques.paperid
     *
     * @return the value of paperandques.paperid
     *
     * @mbg.generated Mon Nov 09 10:13:38 CST 2020
     */
    public Long getPaperid() {
        return paperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paperandques.paperid
     *
     * @param paperid the value for paperandques.paperid
     *
     * @mbg.generated Mon Nov 09 10:13:38 CST 2020
     */
    public void setPaperid(Long paperid) {
        this.paperid = paperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paperandques.questionid
     *
     * @return the value of paperandques.questionid
     *
     * @mbg.generated Mon Nov 09 10:13:38 CST 2020
     */
    public Long getQuestionid() {
        return questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paperandques.questionid
     *
     * @param questionid the value for paperandques.questionid
     *
     * @mbg.generated Mon Nov 09 10:13:38 CST 2020
     */
    public void setQuestionid(Long questionid) {
        this.questionid = questionid;
    }
}