package com.liugx.testsystem.model;

public class PaperAndQuestion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paperandques.paper_id
     *
     * @mbg.generated Fri Dec 11 14:25:25 CST 2020
     */
    private Long paperId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paperandques.question_id
     *
     * @mbg.generated Fri Dec 11 14:25:25 CST 2020
     */
    private Long questionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paperandques.paper_id
     *
     * @return the value of paperandques.paper_id
     *
     * @mbg.generated Fri Dec 11 14:25:25 CST 2020
     */
    public Long getPaperId() {
        return paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paperandques.paper_id
     *
     * @param paperId the value for paperandques.paper_id
     *
     * @mbg.generated Fri Dec 11 14:25:25 CST 2020
     */
    public void setPaperId(Long paperId) {
        this.paperId = paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paperandques.question_id
     *
     * @return the value of paperandques.question_id
     *
     * @mbg.generated Fri Dec 11 14:25:25 CST 2020
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paperandques.question_id
     *
     * @param questionId the value for paperandques.question_id
     *
     * @mbg.generated Fri Dec 11 14:25:25 CST 2020
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }
}