package com.liugx.testsystem.model;

public class Question {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.id
     *
     * @mbg.generated Wed Nov 18 12:08:04 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.head
     *
     * @mbg.generated Wed Nov 18 12:08:04 CST 2020
     */
    private String head;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.answer_a
     *
     * @mbg.generated Wed Nov 18 12:08:04 CST 2020
     */
    private String answerA;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.answer_b
     *
     * @mbg.generated Wed Nov 18 12:08:04 CST 2020
     */
    private String answerB;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.answer_c
     *
     * @mbg.generated Wed Nov 18 12:08:04 CST 2020
     */
    private String answerC;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.answer_d
     *
     * @mbg.generated Wed Nov 18 12:08:04 CST 2020
     */
    private String answerD;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.answer
     *
     * @mbg.generated Wed Nov 18 12:08:04 CST 2020
     */
    private String answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.status
     *
     * @mbg.generated Wed Nov 18 12:08:04 CST 2020
     */
    private Boolean status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.id
     *
     * @return the value of question.id
     *
     * @mbg.generated Wed Nov 18 12:08:04 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.id
     *
     * @param id the value for question.id
     *
     * @mbg.generated Wed Nov 18 12:08:04 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.head
     *
     * @return the value of question.head
     *
     * @mbg.generated Wed Nov 18 12:08:04 CST 2020
     */
    public String getHead() {
        return head;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.head
     *
     * @param head the value for question.head
     *
     * @mbg.generated Wed Nov 18 12:08:04 CST 2020
     */
    public void setHead(String head) {
        this.head = head == null ? null : head.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.answer_a
     *
     * @return the value of question.answer_a
     *
     * @mbg.generated Wed Nov 18 12:08:04 CST 2020
     */
    public String getAnswerA() {
        return answerA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.answer_a
     *
     * @param answerA the value for question.answer_a
     *
     * @mbg.generated Wed Nov 18 12:08:04 CST 2020
     */
    public void setAnswerA(String answerA) {
        this.answerA = answerA == null ? null : answerA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.answer_b
     *
     * @return the value of question.answer_b
     *
     * @mbg.generated Wed Nov 18 12:08:04 CST 2020
     */
    public String getAnswerB() {
        return answerB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.answer_b
     *
     * @param answerB the value for question.answer_b
     *
     * @mbg.generated Wed Nov 18 12:08:04 CST 2020
     */
    public void setAnswerB(String answerB) {
        this.answerB = answerB == null ? null : answerB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.answer_c
     *
     * @return the value of question.answer_c
     *
     * @mbg.generated Wed Nov 18 12:08:04 CST 2020
     */
    public String getAnswerC() {
        return answerC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.answer_c
     *
     * @param answerC the value for question.answer_c
     *
     * @mbg.generated Wed Nov 18 12:08:04 CST 2020
     */
    public void setAnswerC(String answerC) {
        this.answerC = answerC == null ? null : answerC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.answer_d
     *
     * @return the value of question.answer_d
     *
     * @mbg.generated Wed Nov 18 12:08:04 CST 2020
     */
    public String getAnswerD() {
        return answerD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.answer_d
     *
     * @param answerD the value for question.answer_d
     *
     * @mbg.generated Wed Nov 18 12:08:04 CST 2020
     */
    public void setAnswerD(String answerD) {
        this.answerD = answerD == null ? null : answerD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.answer
     *
     * @return the value of question.answer
     *
     * @mbg.generated Wed Nov 18 12:08:04 CST 2020
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.answer
     *
     * @param answer the value for question.answer
     *
     * @mbg.generated Wed Nov 18 12:08:04 CST 2020
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.status
     *
     * @return the value of question.status
     *
     * @mbg.generated Wed Nov 18 12:08:04 CST 2020
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.status
     *
     * @param status the value for question.status
     *
     * @mbg.generated Wed Nov 18 12:08:04 CST 2020
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }
}