package com.liugx.testsystem.model;

public class Test {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.id
     *
     * @mbg.generated Fri Dec 11 14:25:25 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.name
     *
     * @mbg.generated Fri Dec 11 14:25:25 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.create_time
     *
     * @mbg.generated Fri Dec 11 14:25:25 CST 2020
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.modify_time
     *
     * @mbg.generated Fri Dec 11 14:25:25 CST 2020
     */
    private Long modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.start_time
     *
     * @mbg.generated Fri Dec 11 14:25:25 CST 2020
     */
    private Long startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.end_time
     *
     * @mbg.generated Fri Dec 11 14:25:25 CST 2020
     */
    private Long endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.status
     *
     * @mbg.generated Fri Dec 11 14:25:25 CST 2020
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.paper_id
     *
     * @mbg.generated Fri Dec 11 14:25:25 CST 2020
     */
    private Long paperId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.duration
     *
     * @mbg.generated Fri Dec 11 14:25:25 CST 2020
     */
    private Long duration;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.id
     *
     * @return the value of test.id
     *
     * @mbg.generated Fri Dec 11 14:25:25 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.id
     *
     * @param id the value for test.id
     *
     * @mbg.generated Fri Dec 11 14:25:25 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.name
     *
     * @return the value of test.name
     *
     * @mbg.generated Fri Dec 11 14:25:25 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.name
     *
     * @param name the value for test.name
     *
     * @mbg.generated Fri Dec 11 14:25:25 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.create_time
     *
     * @return the value of test.create_time
     *
     * @mbg.generated Fri Dec 11 14:25:25 CST 2020
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.create_time
     *
     * @param createTime the value for test.create_time
     *
     * @mbg.generated Fri Dec 11 14:25:25 CST 2020
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.modify_time
     *
     * @return the value of test.modify_time
     *
     * @mbg.generated Fri Dec 11 14:25:25 CST 2020
     */
    public Long getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.modify_time
     *
     * @param modifyTime the value for test.modify_time
     *
     * @mbg.generated Fri Dec 11 14:25:25 CST 2020
     */
    public void setModifyTime(Long modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.start_time
     *
     * @return the value of test.start_time
     *
     * @mbg.generated Fri Dec 11 14:25:25 CST 2020
     */
    public Long getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.start_time
     *
     * @param startTime the value for test.start_time
     *
     * @mbg.generated Fri Dec 11 14:25:25 CST 2020
     */
    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.end_time
     *
     * @return the value of test.end_time
     *
     * @mbg.generated Fri Dec 11 14:25:25 CST 2020
     */
    public Long getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.end_time
     *
     * @param endTime the value for test.end_time
     *
     * @mbg.generated Fri Dec 11 14:25:25 CST 2020
     */
    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.status
     *
     * @return the value of test.status
     *
     * @mbg.generated Fri Dec 11 14:25:25 CST 2020
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.status
     *
     * @param status the value for test.status
     *
     * @mbg.generated Fri Dec 11 14:25:25 CST 2020
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.paper_id
     *
     * @return the value of test.paper_id
     *
     * @mbg.generated Fri Dec 11 14:25:25 CST 2020
     */
    public Long getPaperId() {
        return paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.paper_id
     *
     * @param paperId the value for test.paper_id
     *
     * @mbg.generated Fri Dec 11 14:25:25 CST 2020
     */
    public void setPaperId(Long paperId) {
        this.paperId = paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.duration
     *
     * @return the value of test.duration
     *
     * @mbg.generated Fri Dec 11 14:25:25 CST 2020
     */
    public Long getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.duration
     *
     * @param duration the value for test.duration
     *
     * @mbg.generated Fri Dec 11 14:25:25 CST 2020
     */
    public void setDuration(Long duration) {
        this.duration = duration;
    }
}