package com.liugx.testsystem.model;

public class UserAndTest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userandtest.id
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userandtest.user_id
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userandtest.test_id
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    private Long testId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userandtest.create_time
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userandtest.modify_time
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    private Long modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userandtest.status
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userandtest.start_time
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    private Long startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userandtest.end_time
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    private Long endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userandtest.score
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userandtest.id
     *
     * @return the value of userandtest.id
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userandtest.id
     *
     * @param id the value for userandtest.id
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userandtest.user_id
     *
     * @return the value of userandtest.user_id
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userandtest.user_id
     *
     * @param userId the value for userandtest.user_id
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userandtest.test_id
     *
     * @return the value of userandtest.test_id
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    public Long getTestId() {
        return testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userandtest.test_id
     *
     * @param testId the value for userandtest.test_id
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    public void setTestId(Long testId) {
        this.testId = testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userandtest.create_time
     *
     * @return the value of userandtest.create_time
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userandtest.create_time
     *
     * @param createTime the value for userandtest.create_time
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userandtest.modify_time
     *
     * @return the value of userandtest.modify_time
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    public Long getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userandtest.modify_time
     *
     * @param modifyTime the value for userandtest.modify_time
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    public void setModifyTime(Long modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userandtest.status
     *
     * @return the value of userandtest.status
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userandtest.status
     *
     * @param status the value for userandtest.status
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userandtest.start_time
     *
     * @return the value of userandtest.start_time
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    public Long getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userandtest.start_time
     *
     * @param startTime the value for userandtest.start_time
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userandtest.end_time
     *
     * @return the value of userandtest.end_time
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    public Long getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userandtest.end_time
     *
     * @param endTime the value for userandtest.end_time
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userandtest.score
     *
     * @return the value of userandtest.score
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userandtest.score
     *
     * @param score the value for userandtest.score
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}