package com.liugx.testsystem.model;

public class UserTestInfoKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertestinfo.user_id
     *
     * @mbg.generated Wed Nov 18 12:08:04 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertestinfo.test_id
     *
     * @mbg.generated Wed Nov 18 12:08:04 CST 2020
     */
    private Long testId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertestinfo.question_id
     *
     * @mbg.generated Wed Nov 18 12:08:04 CST 2020
     */
    private Long questionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertestinfo.user_id
     *
     * @return the value of usertestinfo.user_id
     *
     * @mbg.generated Wed Nov 18 12:08:04 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertestinfo.user_id
     *
     * @param userId the value for usertestinfo.user_id
     *
     * @mbg.generated Wed Nov 18 12:08:04 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertestinfo.test_id
     *
     * @return the value of usertestinfo.test_id
     *
     * @mbg.generated Wed Nov 18 12:08:04 CST 2020
     */
    public Long getTestId() {
        return testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertestinfo.test_id
     *
     * @param testId the value for usertestinfo.test_id
     *
     * @mbg.generated Wed Nov 18 12:08:04 CST 2020
     */
    public void setTestId(Long testId) {
        this.testId = testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertestinfo.question_id
     *
     * @return the value of usertestinfo.question_id
     *
     * @mbg.generated Wed Nov 18 12:08:04 CST 2020
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertestinfo.question_id
     *
     * @param questionId the value for usertestinfo.question_id
     *
     * @mbg.generated Wed Nov 18 12:08:04 CST 2020
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }
}