package com.liugx.testsystem.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.create_t
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    private Long createT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.modified_t
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    private Long modifiedT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.student_num
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    private String studentNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.create_t
     *
     * @return the value of user.create_t
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    public Long getCreateT() {
        return createT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.create_t
     *
     * @param createT the value for user.create_t
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    public void setCreateT(Long createT) {
        this.createT = createT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.modified_t
     *
     * @return the value of user.modified_t
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    public Long getModifiedT() {
        return modifiedT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.modified_t
     *
     * @param modifiedT the value for user.modified_t
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    public void setModifiedT(Long modifiedT) {
        this.modifiedT = modifiedT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.student_num
     *
     * @return the value of user.student_num
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    public String getStudentNum() {
        return studentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.student_num
     *
     * @param studentNum the value for user.student_num
     *
     * @mbg.generated Wed Dec 16 08:34:14 CST 2020
     */
    public void setStudentNum(String studentNum) {
        this.studentNum = studentNum == null ? null : studentNum.trim();
    }
}